export component Page inherits Rectangle {
    in property<string> header <=> h.text;
    background: transparent;
    in property <bool> has-back-button: false;
    callback back;

    TouchArea {} // protect underneath controls

    if (root.has-back-button) : Image {
        x:0;
        source: @image-url("../images/back.svg");
        image-fit: contain;
        y: h.y + (h.height - self.height) / 2;
        width: 14px;
        height: 24px;
        TouchArea {
            x:0;
            clicked => { root.back() }
            width: 150%;
        }
    }

    h := Text {
        font-weight: 900;
        font-size: 20px * 2;
        color: #f7f7f7;
        y: 46px - self.font-size;
        x: root.has-back-button ? 24px + 16px : 0px;
        // Allow clicking on the title as well to get back easier when just
        // using fingers on a small screen.
        if (root.has-back-button) : TouchArea {
            clicked => { root.back() }
        }
    }
}
